name: twenty_eight
description: Your first step into pesonal finance.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  bloc: ^8.0.3
  flex_color_scheme: ^5.0.1
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20
  cloud_firestore: ^3.1.18
  hooks_riverpod: ^1.0.4
  google_fonts: ^3.0.1
  salomon_bottom_bar: ^3.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
