name: twenty_eight
description: Your first step into personal finance.
version: 0.0.4
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  bloc: ^8.0.3
  cloud_firestore: ^3.1.18
  equatable: ^2.0.3
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  flex_color_scheme: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^3.0.1
  hooks_riverpod: ^1.0.4
  intl: ^0.17.0
  json_annotation: ^4.5.0
  salomon_bottom_bar: ^3.3.1

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
